services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ikon/auto-muter-backend:latest
    volumes:
      - ../browser-extension/backend:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16g'
    environment:
      - HF_AUTH_TOKEN

networks:
  default:
    driver: bridge
    name: auto-muter