services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ikon/auto-muter-backend:latest-1
    volumes:
      - ..:/app
      - /data:/data
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["uvicorn", "browser-extension.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16g'
    environment:
      - HF_AUTH_TOKEN
    user: "${PUID}:${PGID}"

networks:
  default:
    driver: bridge
    name: auto-muter