services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ikon/auto-muter-backend:aws-cpu
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: sh -c "python -X utf8 -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    shm_size: '2g'
    environment:
      - HF_AUTH_TOKEN
      - PYTHONIOENCODING


networks:
  default:
    driver: bridge
    name: auto-muter